### ISSUE TITLE
Questions on the multi-level approach

### ISSUE THREAD

**Issue by alzaia** [vsomnath/holoprot#2]
Hello guys, I really enjoyed the paper and the approach of combining different levels of protein representation. I was wondering if I could try a similar approach with my use case. I do not work on the surface level, but I more interested in combining the residue level of my graph (let's call this residue graph Gr) and the more fine-grained atom level (Ga). I can relate each residue node of Gr to many atom nodes from Ga. My questions to you would be:
1. Would that approach be doable in my case (from your intuition)?
2. If yes, I am mostly interested in the part of your code that takes care of the update and messaging between the 2 levels (i.e. the computation of hidden features hr for graph Gr, the creation of the new mapping x for graph Ga, then the computation of embeddings ha, and finally the aggregation of original graph embeddings c). Can you guys point me to the methods/code of interest in the repository? 

Thanks a lot! Great work!

**Comment by alzaia** [comment]
I guess the class of interest would be https://github.com/vsomnath/holoprot/blob/main/holoprot/layers/mpn/prot_mpn.py, right?

**Comment by vsomnath** [comment]
Hi alzaia, thank you for your interest and sorry for the slow response. 

Yes, the approach should be doable and has been employed as an encoder in this work - https://arxiv.org/abs/2207.06616 
The methods / code of interest in the repository would be: 

1. https://github.com/vsomnath/holoprot/blob/main/holoprot/layers/mpn/prot_mpn.py (MPN Class)
2. https://github.com/vsomnath/holoprot/blob/main/holoprot/graphs/hier_graph.py (Graph Preparation)

Please let me know if there are any bugs in the code, or something is unclear!

Best,
Vignesh

**Comment by vsomnath** [comment]
Closing this for now, feel free to reopen if necessary
